config/routes.rb
Rails.application.routes.draw do
  devise_scope :resident do
    root "public/sessions#new"
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :residents, controllers: {
    sessions: 'public/sessions',
    registrations: 'admin/resident/registrations',
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
  }

  namespace :admin do
    get '/events/new', to: 'admin_events#new', as: 'new_events'
    get '/events', to: 'admin_events#index', as: 'events'
    get '/events/:id/edit', to: 'admin_events#edit', as: 'edit_event'
    post '/events/new', to: 'admin_events#create', as: 'event'
    patch '/events/:id', to: 'admin_events#update'
    delete '/events/:id', to: 'admin_events#destroy'
    resources :posts
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :residents, only: [:index, :show, :edit, :update] do
      resources :photos, only: [:index, :new, :create, :destroy]
      resources :households, only: [:new, :create, :edit, :update]
    end
  end

  scope module: :admin do
    resources :admins, only: [:index]
    get '/admins/:id', to: 'admins#show', as: 'admin_info'
    resources :meals, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    get 'information', to: 'homes#information'
    get '/mypage', to: 'residents#show'
    get '/edit', to: 'residents#edit'
    get '/confirm', to: 'residents#confirm'
    patch '/edit', to: 'residents#update'
    resources :photos, only: [:index]
    resources :messages, only: [:index]
    resources :myevents, only: [:new, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    get '/bookmarks', to: 'bookmarks#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resident.rb
require 'concerns/full_name'
require 'concerns/age'

class Resident < ApplicationRecord

  include FullName
  include Age

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :household, optional: true
  has_many :photos, dependent: :destroy
  has_many :myevents, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :login_id, presence: true
  validates :date_of_birth, presence: true
  validates :gender, presence: true
  validates :self_message, length: { maximum: 20 }

  enum gender: { man: 0, woman: 1 }

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # ゲストログインメソッド
  def self.guest
    find_or_create_by!(first_name: '太郎', last_name: 'ゲスト', first_name_kana: 'タロウ', last_name_kana: 'ゲスト', phone_number: '00011112222', date_of_birth: '2000-01-01', login_id: 'guest.login') do |resident|
      resident.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/resident/confirmations_controller.rb
# frozen_string_literal: true

class Public::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/resident/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Public::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/resident/passwords_controller.rb
# frozen_string_literal: true

class Public::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/resident/registrations_controller.rb
# frozen_string_literal: true

class Admin::Resident::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:cancel]
  # prepend_before_action :authenticate_scope!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :date_of_birth,
      :phone_number,
      :login_id,
      :information,
      :gender,
    ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    admin_resident_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/resident/unlocks_controller.rb
# frozen_string_literal: true

class Public::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/residents_controller.rb
class Admin::ResidentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_resident, only: [:show, :edit, :update]

  def index
    @q = Resident.ransack(params[:q])
    @households = Household.all
    @residents = @q.result.includes(:household).page(params[:page]).per(20)
  end

  def show
    if @resident.household.present?
      @household = @resident.household
      @residents = @household.residents
    end
  end

  def edit
    @households = Household.all
  end

  def update
    @households = Household.all
    if @resident.update(resident_params)
      redirect_to admin_resident_path(@resident), notice: "#{@resident.full_name}さんの情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def set_resident
    @resident = Resident.find(params[:id])
  end

  def resident_params
    params.require(:resident).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :login_id, :date_of_birth, :gender, :information, :household_id, :has_left)
  end

  def search_params
    params.require(:q).permit(:last_name_cont, :household_id_eq)
  end
end

app/helpers/admin/residents_helper.rb
module Admin::ResidentsHelper
end

app/views/admin/residents/edit.html.slim
h2 編集する

.registration-form-container
  = render 'layouts/error_messages', resource: @resident
  = form_with model: [:admin, @resident], class: 'registration-form', local: true do |f|
    .form-body
      .form-row
        .form-group.col-lg-6.col-md-6.col-sm-6
          = f.label :last_name
          = f.text_field :last_name, autofocus: true, class:'form-control'
        .form-group.col-lg-6.col-md-6.col-sm-6
          = f.label :first_name
          span.required 【必須】
          = f.text_field :first_name, autofocus: true, class:'form-control'

      .form-row
        .form-group.col-lg-6.col-md-6.col-sm-6
          = f.label :last_name_kana
          = f.text_field :last_name_kana, autofocus: true, class:'form-control'
        .form-group.col-lg-6.col-md-6.col-sm-6
          = f.label :first_name_kana
          span.required 【必須】
          = f.text_field :first_name_kana, autofocus: true, class:'form-control'

      .form-group
        = f.label :phone_number
        span.required 【必須】
        = f.text_field :phone_number, autofocus: true, class:'form-control'

      .form-group
        = f.label :login_id
        span.required 【必須】
        = f.text_field :login_id, autofocus: true, class:'form-control'

      .form-group
        = f.label :date_of_birth
        span.required 【必須】
        br
        = f.date_select :date_of_birth, {use_birth_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1981, 1, 1)}, {class: 'form-control', style: 'display: inline-block;width: auto;' }

      .form-group
        = f.label :gender, "性別", { class: 'form-check-label' }
        span.required 【必須】
        br
        = f.radio_button :gender, 'man', :checked => true
        = f.label :gender, "男性", { class: 'form-check-label mr-2' }
        = f.radio_button :gender, 'woman'
        = f.label :gender, "女性", { class: 'form-check-label' }

      .form-group
        = f.label :information
        span.optional 【任意】
        = f.text_area :information, rows: 5, autofocus: true, class:'form-control'

      .form-group
        = f.label :household_id, '世帯登録'
        = f.select :household_id, @households.map{ |household| [household.information, household.id] }, { include_blank: '選択してください' }, { class:'form-control' }

      .form-group
        = f.label :has_left, "入所状況"
        br
        = f.radio_button :has_left, false, :checked => true
        = f.label :has_left, "入所中", { class: 'form-check-label mr-2' }
        = f.radio_button :has_left, true
        = f.label :has_left, "退所済"


    = f.submit "変更", class: 'edit-btn'

app/views/admin/residents/index.html.slim
.title-container
  = image_tag 'icon-people.png', width: '80px', height: '80px', class: 'photo-icon'
  h2 避難者一覧

.resident-search-container
  = search_form_for @q, url: admin_residents_path, class: 'search-form' do |f|
    .input-container
      .form-group.row
        = f.label :last_name_cont, '名前', class: 'col-lg-4 col-md-4 col-form-label search-label'
        .col-md-8.col-lg-7
          = f.search_field :last_name_cont, class: 'form-control'
      .form-group.row
        = f.label :household_id_eq, '居住スペース', class: 'col-lg-4 col-md-4 col-form-label search-label'
        .col-md-8.col-lg-7
          = f.collection_select :household_id_eq, @households, :id, :living_space, :include_blank => '指定なし', class: 'form-control'
    = f.submit class: 'submit-btn'

.resident-table-container
  table.resident-table
    tbody
      tr
        th= sort_link(@q, :last_name, "避難者名", [:last_name, "gender"])
        th= sort_link(@q, :date_of_birth, "年齢")
        th= sort_link(@q, :gender)
        th 居住スペース
        th 自宅住所
        th 写真許可
      - @residents.each do |resident|
        tr
          td= link_to resident.full_name, admin_resident_path(resident), class: 'name'
          td= "#{resident.age}才"
          td= resident.gender_i18n
          - if resident.household.present?
            td= resident.household.living_space
            td= resident.household.address
          - else
            td 世帯情報を登録してください
            td 世帯情報を登録してください
          - if resident.photo_accepted?
            td 許可する
          - else
            td 許可しない
  = link_to "避難者新規登録へ", new_resident_registration_path, class: 'new-resident-btn'


  = paginate @residents
  .pagination-count
    = page_entries_info @residents

app/views/admin/residents/show.html.slim
h2= "#{@resident.full_name}さん"

.resident-container
  table.resident-show-table
    tbody
      tr
        th 名前
        td
          = @resident.full_name_kana
          br
          = @resident.full_name
      tr
        th 性別
        td= @resident.gender_i18n

      tr
        th 生年月日
        td= @resident.birthday
      tr
        th 年齢
        td= "#{@resident.age}才"
      tr
        th 連絡先
        td= @resident.phone_number
      tr
        th ログインID
        td= @resident.login_id
      tr
        th 避難者情報
        td= @resident.information
      tr
        th 避難者情報
        - if @resident.has_left?
          td 退所済み
        - else
          td 入所中
      tr
        th 写真許可
        - if @resident.photo_accepted?
          td 許可する
        - else
          td 許可しない
  .btn-link
    = link_to "編集する", edit_admin_resident_path, class: 'resident-edit-btn'
    - if @resident.photo_accepted?
      = link_to "写真アルバムへ", admin_resident_photos_path(@resident), class: 'photo-btn'

.resident-container
  - if @resident.household.present?
    table.resident-show-table
      tbody
        tr
          th.title colspan=2 世帯情報
        tr
          th 世帯主名
          td= @household.full_name
        tr
          th 住所
          td= @household.address
        tr
          th 家屋被害状況
          td= @household.house_damage_situation
        tr
          th 居住スペース
          td= @household.living_space
        tr
        tr
          th 世帯メンバー
          td
            - @residents.each do |resident|
              br
              = link_to resident.full_name, admin_resident_path(resident)

    = link_to "世帯情報を編集する", edit_admin_resident_household_path(@resident, @household), class: 'edit-btn'

  - else
    = link_to '世帯情報を登録する', new_admin_resident_household_path(@resident), class: 'edit-btn'