config/routes.rb
Rails.application.routes.draw do
  devise_scope :resident do
    root "public/sessions#new"
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :residents, controllers: {
    sessions: 'public/sessions',
    registrations: 'admin/resident/registrations',
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
  }

  namespace :admin do
    get '/events/new', to: 'admin_events#new', as: 'new_events'
    get '/events', to: 'admin_events#index', as: 'events'
    get '/events/:id/edit', to: 'admin_events#edit', as: 'edit_event'
    post '/events/new', to: 'admin_events#create', as: 'event'
    patch '/events/:id', to: 'admin_events#update'
    delete '/events/:id', to: 'admin_events#destroy'
    resources :posts
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :residents, only: [:index, :show, :edit, :update] do
      resources :photos, only: [:index, :new, :create, :destroy]
      resources :households, only: [:new, :create, :edit, :update]
    end
  end

  scope module: :admin do
    resources :admins, only: [:index]
    get '/admins/:id', to: 'admins#show', as: 'admin_info'
    resources :meals, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    get 'information', to: 'homes#information'
    get '/mypage', to: 'residents#show'
    get '/edit', to: 'residents#edit'
    get '/confirm', to: 'residents#confirm'
    patch '/edit', to: 'residents#update'
    resources :photos, only: [:index]
    resources :messages, only: [:index]
    resources :myevents, only: [:new, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    get '/bookmarks', to: 'bookmarks#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  validates :sender, presence: true
  mount_uploader :image, MessageUploader
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @messages = Message.page(params[:page]).per(6).order(created_at: :desc)
    @message = Message.new
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to admin_messages_url, notice: "メッセージを追加しました。"
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to admin_messages_url, notice: "メッセージを削除しました。"
  end

  private

  def message_params
    params.require(:message).permit(:image, :content, :sender)
  end
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/views/admin/messages/_index.html.slim
.messages-index
  - messages.each do |message|
    .message-item
      - if message.image.present?
        = image_tag message.image.url, class: 'message-img'
      .card-body
        - if message.content.present?
          p.message-content= message.content
        p.sender= "#{message.sender} さんより"
        - if admin_signed_in?
          span.delete-message
            = link_to '削除', admin_message_path(message.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'delete-message-link'

app/views/admin/messages/index.html.slim
.title-container
  = image_tag 'icon-message.png', width: '80px', height: '80px', class: 'photo-icon'
  h2 全国からのメッセージ

= link_to 'メッセージ追加', new_admin_message_path, class: 'new-message-btn'

= render 'admin/messages/index', messages: @messages


= paginate @messages
.pagination-count
  = page_entries_info @messages

app/views/admin/messages/new.html.slim
h2 メッセージ追加

.form-container
  = render 'layouts/error_messages', resource: @message
  = form_with model: [:admin, @message], class: 'form', local: true do |f|
    .form-body
      .form-group
        = f.label :sender
        span.required 【必須】
        = f.text_field :sender, class:'form-control'
      .form-group
        = f.label :content
        span.optional 【任意】
        = f.text_area :content, rows: 10, class:'form-control'
      .form-group
        = f.label :image
        span.optional 【任意】
        = f.file_field :image, class: 'form-control'
    = f.submit nil, class: 'new-btn'