config/routes.rb
Rails.application.routes.draw do
  devise_scope :resident do
    root "public/sessions#new"
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :residents, controllers: {
    sessions: 'public/sessions',
    registrations: 'admin/resident/registrations',
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
  }

  namespace :admin do
    get '/events/new', to: 'admin_events#new', as: 'new_events'
    get '/events', to: 'admin_events#index', as: 'events'
    get '/events/:id/edit', to: 'admin_events#edit', as: 'edit_event'
    post '/events/new', to: 'admin_events#create', as: 'event'
    patch '/events/:id', to: 'admin_events#update'
    delete '/events/:id', to: 'admin_events#destroy'
    resources :posts
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :residents, only: [:index, :show, :edit, :update] do
      resources :photos, only: [:index, :new, :create, :destroy]
      resources :households, only: [:new, :create, :edit, :update]
    end
  end

  scope module: :admin do
    resources :admins, only: [:index]
    get '/admins/:id', to: 'admins#show', as: 'admin_info'
    resources :meals, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    get 'information', to: 'homes#information'
    get '/mypage', to: 'residents#show'
    get '/edit', to: 'residents#edit'
    get '/confirm', to: 'residents#confirm'
    patch '/edit', to: 'residents#update'
    resources :photos, only: [:index]
    resources :messages, only: [:index]
    resources :myevents, only: [:new, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    get '/bookmarks', to: 'bookmarks#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
require 'concerns/full_name'
require 'concerns/age'

class Admin < ApplicationRecord

  include FullName
  include Age
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :phone_number, presence: true
  validates :login_id, presence: true
  validates :date_of_birth, presence: true
  validates :email, presence: true, uniqueness: true

  # ゲストログインメソッド
  def self.guest
    find_or_create_by!(first_name: '太郎', last_name: '管理', first_name_kana: 'タロウ', last_name_kana: 'カンリ', email: 'guest@admin.com', phone_number: '00011112222', date_of_birth: '2000-01-01', login_id: 'guest.login') do |admin|
      admin.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/admin_event.rb
require 'concerns/time'

class AdminEvent < ApplicationRecord
  include TimeFormat
  
  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  
  scope :for_today, -> { where(start: Time.now.in_time_zone("Tokyo").all_day) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :resident
  belongs_to :post
end

app/models/concerns/age.rb
module Age
  def date_format
    '%Y/%-m/%-d'
  end

  def birthday
    date_of_birth.strftime(date_format)
  end

  def age
    (Date.today.strftime(date_format).to_i - birthday.to_i)
  end
end

app/models/concerns/full_name.rb
module FullName
  def full_name
    last_name + " " + first_name
  end

  def full_name_kana
    last_name_kana + " " + first_name_kana
  end
end

app/models/concerns/time.rb
module TimeFormat
  def time
    start.strftime("%H:%M")
  end

  def time_format
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    created_at.strftime("%-m/%-d(#{wd[created_at.wday]})")
  end
end

app/models/household.rb
class Household < ApplicationRecord
  has_many :residents

  validates :head_first_name, presence: true
  validates :head_last_name, presence: true
  validates :address, presence: true, uniqueness: true
  validates :house_damage_situation, presence: true
  validates :living_space, presence: true

  def information
    head_last_name + head_first_name + '　' + address
  end

  def full_name
    head_last_name + ' ' + head_first_name
  end
end

app/models/meal.rb
require 'concerns/time'

class Meal < ApplicationRecord
  include TimeFormat

  validates :menu, presence: true
  validates :amount, presence: true
  validates :start, presence: true

  scope :for_today, -> { where(start: Time.now.in_time_zone("Tokyo").all_day) }
end

app/models/message.rb
class Message < ApplicationRecord
  validates :sender, presence: true
  mount_uploader :image, MessageUploader
end

app/models/myevent.rb
require 'concerns/time'

class Myevent < ApplicationRecord
  include TimeFormat

  belongs_to :resident

  validates :title, presence: true
  validates :resident_id, presence: true
  validates :start, presence: true

  scope :for_today, -> { where(start: Time.now.in_time_zone("Tokyo").all_day) }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :resident
  mount_uploaders :image, ResidentPhotoUploader
  serialize :image, JSON

  validates :resident_id, presence: true
  validates :image, presence: true
end

app/models/post.rb
require 'concerns/time'

class Post < ApplicationRecord
  include TimeFormat

  has_many :bookmarks, dependent: :destroy
  belongs_to :admin
  mount_uploaders :image, ImageUploader
  serialize :image, JSON

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 20 }
  validates :admin_id, presence: true

  def bookmarked_by?(resident)
    bookmarks.where(resident_id: resident.id).exists?
  end
end

app/models/resident.rb
require 'concerns/full_name'
require 'concerns/age'

class Resident < ApplicationRecord

  include FullName
  include Age

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :household, optional: true
  has_many :photos, dependent: :destroy
  has_many :myevents, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :phone_number, presence: true
  validates :login_id, presence: true
  validates :date_of_birth, presence: true
  validates :gender, presence: true
  validates :self_message, length: { maximum: 20 }

  enum gender: { man: 0, woman: 1 }

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  # ゲストログインメソッド
  def self.guest
    find_or_create_by!(first_name: '太郎', last_name: 'ゲスト', first_name_kana: 'タロウ', last_name_kana: 'ゲスト', phone_number: '00011112222', date_of_birth: '2000-01-01', login_id: 'guest.login') do |resident|
      resident.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def today
    wd = ["日", "月", "火", "水", "木", "金", "土"]
    today = Date.today
    @today = today.strftime("%-m/%d(#{wd[today.wday]})")
  end
end

app/helpers/admin/meals_helper.rb
module Admin::MealsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/households_helper.rb
module HouseholdsHelper
end

app/views/admin/admins/index.html.slim
.title-container
  = image_tag 'icon-admin.png', width: '80px', height: '80px', class: 'photo-icon'
  h2 管理者一覧

.admin-table-container
  table.admin-table
    tbody
      tr
        th 名前
        th 年齢
        th ログインID
        th 連絡先
        th メールアドレス
      - @admins.each do |admin|
        tr
          td= link_to admin.full_name, admin_info_path(admin)
          td= "#{admin.age}才"
          td= admin.login_id
          td= admin.phone_number
          td= admin.email

  = link_to '管理者新規登録', new_admin_registration_path, class: 'new-admin-btn'

app/views/admin/admins/show.html.slim
h2= "#{@admin.full_name}さん"

.admin-show-container
  table.admin-show-table
    tbody
      tr
        th 名前
        td
          = @admin.full_name_kana
          br
          = @admin.full_name
      tr
        th 年齢
        td= "#{@admin.age}才"
      tr
        th 連絡先
        td= @admin.phone_number
      tr
        th ログインID
        td= @admin.login_id
      tr
        th メールアドレス
        td= @admin.email

app/views/admin/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/admin/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br

app/views/layouts/_error_messages.html.slim
- if resource.errors.present?
  ul#error_explanation
    - resource.errors.full_messages.each do |message|
      li.error-message= message

app/views/layouts/_header.html.slim
    p.logo ともしび
    ul
      - if admin_signed_in?
        li.list-item
          = link_to admin_events_path, class:'header-link' do
            = image_tag 'icon-calendar.png', width: '80px', height: '80px'
            p.list-text 避難所カレンダー
        li.list-item
          = link_to admin_residents_path, class:'header-link' do
            = image_tag 'icon-people.png', width: '80px', height: '80px'
            p.list-text 避難者一覧
        li.list-item
          = link_to admin_posts_path, class:'header-link' do
            = image_tag 'icon-news.png', width: '80px', height: '80px'
            p.list-text 避難所通信一覧
        li.list-item
          = link_to meals_path, class:'header-link' do
            = image_tag 'icon-rice.png', width: '80px', height: '80px'
            p.list-text 献立
        li.list-item
          = link_to admin_messages_path, class:'header-link' do
            = image_tag 'icon-message.png', width: '80px', height: '80px'
            p.list-text メッセージ
        li.list-item
          = link_to admins_path, class:'header-link' do
            = image_tag 'icon-admin.png', width: '80px', height: '80px'
            p.list-text 管理者一覧
        li.list-item
           = link_to information_path, class:'header-link' do
            = image_tag 'icon-info.png', width: '80px', height: '80px'
            p.list-text 避難所情報
        li.list-item
          = link_to destroy_admin_session_path, method: :delete, class:'header-link' do
            = image_tag 'icon-logout.png', width: '80px', height: '80px'
            p.list-text ログアウト

      - elsif resident_signed_in?
        li.list-item
           = link_to mypage_path, class:'header-link' do
            = image_tag 'mypage.png', width: '80px', height: '80px'
            p.list-text マイページ
        li.list-item
           = link_to posts_path, class:'header-link' do
            = image_tag 'icon-news.png', width: '80px', height: '80px'
            p.list-text 避難所通信
        li.list-item
           = link_to bookmarks_path, class:'header-link' do
            = image_tag 'icon-bookmark.png', width: '80px', height: '80px'
            p.list-text お気に入り
        li.list-item
           = link_to messages_path, class:'header-link' do
            = image_tag 'icon-message.png', width: '80px', height: '80px'
            p.list-text メッセージ
        li.list-item
           = link_to meals_path, class:'header-link' do
            = image_tag 'icon-rice.png', width: '80px', height: '80px'
            p.list-text 献立
        li.list-item
          - if current_resident.photo_accepted
            = link_to photos_path, class:'header-link' do
              = image_tag 'icon-photo.png', width: '80px', height: '80px'
              p.list-text 写真アルバム
          - else
            = link_to confirm_path, class:'header-link' do
              = image_tag 'icon-photo.png', width: '80px', height: '80px'
              p.list-text 写真アルバム
        li.list-item
           = link_to information_path, class:'header-link' do
            = image_tag 'icon-info.png', width: '80px', height: '80px'
            p.list-text 避難所情報
        li.list-item
           = link_to destroy_resident_session_path, method: :delete, class:'header-link' do
            = image_tag 'icon-logout.png', width: '80px', height: '80px'
            p.list-text ログアウト

      - else
        li.list-item
          = link_to new_admin_session_path, class:'header-link' do
            = image_tag 'icon-login.png', width: '80px', height: '80px'
            p.list-text 管理者ログイン

          li.list-item
            = link_to new_resident_session_path, class:'header-link' do
              = image_tag 'icon-login.png', width: '80px', height: '80px'
              p.list-text 住民さんログイン

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ともしび
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    .left-side-menu
      = render 'layouts/header'


  .main
    img#open.hamburger-menu src="https://img.icons8.com/metro/26/000000/menu.png"
    .overlay
      img#close.close-menu src="https://img.icons8.com/ios-filled/50/000000/multiply.png"
      = render 'layouts/header'

    - if admin_signed_in? || resident_signed_in?
      .welcome-container
        .welcome-box
          p ともしび避難所
          span.left-bar
          span.right-bar
        - if admin_signed_in?
          .welcome-box
            p= "こんにちは、#{current_admin.full_name}さん！"
            span.left-bar
            span.right-bar
        - elsif resident_signed_in?
          .welcome-box
            p= "#{current_resident.self_message}"
            span.left-bar
            span.right-bar
          .welcome-box.resident-name
            p= "こんにちは、#{current_resident.full_name}さん！"
            span.left-bar
            span.right-bar

    - if flash.notice.present?
      .alert.alert-success= flash.notice
    = yield
    .left-top-triangle
    .right-top-triangle
    .right-bottom-triangle
    .left-bottom-triangle