config/routes.rb
Rails.application.routes.draw do
  devise_scope :resident do
    root "public/sessions#new"
    post '/guest_sign_in', to: 'public/sessions#new_guest'
  end

  devise_scope :admin do
    post 'admin/guest_sign_in', to: 'admin/sessions#new_guest'
  end

  devise_for :residents, controllers: {
    sessions: 'public/sessions',
    registrations: 'admin/resident/registrations',
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    registrations: 'admin/registrations',
  }

  namespace :admin do
    get '/events/new', to: 'admin_events#new', as: 'new_events'
    get '/events', to: 'admin_events#index', as: 'events'
    get '/events/:id/edit', to: 'admin_events#edit', as: 'edit_event'
    post '/events/new', to: 'admin_events#create', as: 'event'
    patch '/events/:id', to: 'admin_events#update'
    delete '/events/:id', to: 'admin_events#destroy'
    resources :posts
    resources :messages, only: [:index, :new, :create, :destroy]
    resources :residents, only: [:index, :show, :edit, :update] do
      resources :photos, only: [:index, :new, :create, :destroy]
      resources :households, only: [:new, :create, :edit, :update]
    end
  end

  scope module: :admin do
    resources :admins, only: [:index]
    get '/admins/:id', to: 'admins#show', as: 'admin_info'
    resources :meals, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  scope module: :public do
    get 'information', to: 'homes#information'
    get '/mypage', to: 'residents#show'
    get '/edit', to: 'residents#edit'
    get '/confirm', to: 'residents#confirm'
    patch '/edit', to: 'residents#update'
    resources :photos, only: [:index]
    resources :messages, only: [:index]
    resources :myevents, only: [:new, :create, :edit, :update, :destroy]
    resources :posts, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
    get '/bookmarks', to: 'bookmarks#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
require 'concerns/time'

class Post < ApplicationRecord
  include TimeFormat

  has_many :bookmarks, dependent: :destroy
  belongs_to :admin
  mount_uploaders :image, ImageUploader
  serialize :image, JSON

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 20 }
  validates :admin_id, presence: true

  def bookmarked_by?(resident)
    bookmarks.where(resident_id: resident.id).exists?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes([:admin]).page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.new(post_params)
    if @post.save
      redirect_to admin_posts_url, notice: "避難所通信「#{@post.title}」を投稿しました。"
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_url(@post), notice: "避難所通信「#{@post.title}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_url, notice: "避難所通信「#{@post.title}」を削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, { image: [] })
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_search.html.slim
.post-search-container
  = search_form_for q, url: admin_posts_path, class: 'search-form' do |f|
    .input-container
      .form-group.row
        = f.label :title_cont, 'タイトル', class: 'col-lg-3 col-md-4 form-label search-label'
        .col-md-8.col-lg-7
          = f.search_field :title_cont, class: 'form-control'
      .form-group.row
        = f.label :body_cont, '内容', class: 'col-lg-3 col-md-4 col-form-label search-label'
        .col-md-8.col-lg-7
          = f.search_field :body_cont, class: 'form-control'
    = f.submit class: 'submit-btn'

app/views/admin/posts/edit.html.slim
h2 避難所通信の編集
.post-edit-form
  = render 'layouts/error_messages', resource: @post
  = form_with model: [:admin, @post], class: 'edit-form', local: true do |f|
    .edit-form-body
      .form-group
        = f.label :title
        span.required 【必須】
        = f.text_field :title, class:'form-control'
      .form-group
        = f.label :body
        span.required 【必須】
        = f.text_area :body, rows: 10, class:'form-control'
      .form-group
        .photos
          - if @post.image.present?
            - @post.image.each do |image|
              = image_tag image.url, id: :image_prev
        = f.file_field :image, id: :post_image, multiple: true, class: 'form-control'
    .center
    = f.submit nil, class: 'update-btn'

app/views/admin/posts/index.html.slim
.title-container
  = image_tag 'icon-news.png', width: '80px', height: '80px', class: 'photo-icon'
  h2 避難所通信

= render 'admin/posts/search', q: @q

.post-table-container
  table.post-table
    - @posts.each do |post|
      tbody
        tr
          th.time= post.time_format
          td= "投稿者: #{post.admin.full_name}"
        tr
          th= link_to post.title, admin_post_path(post), class: "post-title"
        tr
          td.body colspan=3 = simple_format(h(post.body), {}, sanitize: false, wrapper_tag: "div")

  = link_to "新規投稿", new_admin_post_path, class: 'new-posts-btn'


  = paginate @posts
  .pagination-count
    = page_entries_info @posts

app/views/admin/posts/new.html.slim
h2 避難所通信の新規投稿

.form-container
  = render 'layouts/error_messages', resource: @post
  = form_with model: [:admin, @post], class: 'form', local: true do |f|
    .form-body
      .form-group
        = f.label :title
        span.required 【必須】
        = f.text_field :title, class:'form-control'
      .form-group
        = f.label :body
        span.required 【必須】
        = f.text_area :body, rows: 10, class:'form-control'
      .form-group
        = f.label :image
        span.optional 【任意】
        = f.file_field :image, multiple: true, class: 'form-control'
    = f.submit '投稿', class: 'new-btn'

app/views/admin/posts/show.html.slim
.post-show-container

  .post-show
    .show-top
      p.time= @post.time_format
      p.writer= "投稿者: #{@post.admin.full_name}"
    h2= @post.title

    .center
      - if @post.image.present?
        = image_tag @post.image[0].url, id: "bigimg", height: '400px'
        ul
          - @post.image.each do |image|
            li
              = image_tag image.url, height: '100px', class: 'thumb'

    p.body= @post.body

    .btn-container
      = link_to "編集する", edit_admin_post_path(@post), class: 'post-edit-btn'
      = link_to "削除する", admin_post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'post-delete-btn'